version: "1"

volumes:
  mongo-data:
  postgres_data:

services:
  # Mongo database
  mongodb:
    container_name: mongodb
    build:
      context: ./database/movie
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - movie-net

  postgres:
    container_name: notification-db
    build:
      context: ./database/notification
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -p 5432 --username=postgres --dbname=notification",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  movie-net:
    driver: bridge
