version: "1"

services:
  # API to manage account
  recommend-service:
    container_name: recommend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
